name: publish

on:
  push: 
    branches:
      - main
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

env:
  node-version: '20.x'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      #
      # Setup for build
      #
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: node_modules cache
        uses: actions/cache@v2
        id: cache_node_modules
        with:
          # キャッシュキー完全一致しない場合 npm installする必要があるのでrestore-keysは使わない
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          path: '**/node_modules'

      - name: Install Dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install
        
  release-buttons:
    if: contains(github.ref, 'tags/buttons')
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          path: '**/node_modules'
      - name: Build
        run: npm run build:all
      - name: Check if package version can be published
        uses: technote-space/package-version-check-action@v1
        with:
          PACKAGE_DIR: 'packages/buttons/'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_MANAGER: npm
      - name: Publish buttons package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && npm run publish:buttons
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  release-forms:
    if: contains(github.ref, 'tags/forms')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          path: '**/node_modules'
      - name: Build
        run: npm run build:all
      - name: Check if package version can be published
        uses: technote-space/package-version-check-action@v1
        with:
          PACKAGE_DIR: 'packages/forms/'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_MANAGER: npm
      - name: Publish forms package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && npm run publish:forms

  release-all:
    if: contains(github.ref, 'tags/all')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          path: '**/node_modules'
      - name: Build
        run: npm run build:all
      - name: Check if buttons package version can be published
        uses: technote-space/package-version-check-action@v1
        with:
          PACKAGE_DIR: 'packages/buttons/'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_MANAGER: npm
      - name: Check if forms package version can be published
        uses: technote-space/package-version-check-action@v1
        with:
          PACKAGE_DIR: 'packages/forms/'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_MANAGER: npm
      - name: Publish buttons package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && npm run publish:buttons
      - name: Publish forms package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc && npm run publish:forms
